### ISSUE TITLE
[FEAT]: controller/user : Implement CRUD

### ISSUE THREAD

**Issue by sub1120** [lmsGenie/server#8]
**Is your feature request related to a problem? Please describe.**

Feature Details:-
- Controllers: `createUser()` , `getAllUsers()`, `getUserById()`, `updateUserById()`, `deleteUserById()`
- Location: `controllers/v1/user.controller.ts`
- Primary Collection : `user`
- Description : Implement controllers to perform CRUD on given collection

Note: For additional details on schema, check out the design on eraser,

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
<p><a target="_blank" href="https://app.eraser.io/workspace/pPrQuuG2ClvFiEfNcvKf" id="edit-in-eraser-github-link"><img alt="Edit in Eraser" src="https://firebasestorage.googleapis.com/v0/b/second-petal-295822.appspot.com/o/images%2Fgithub%2FOpen%20in%20Eraser.svg?alt=media&amp;token=968381c8-a7e7-472a-8ed6-4a6626da5501"></a></p>

**Comment by MTouthang** [comment]
i'll be working on this

**Comment by sub1120** [comment]
@MTouthang , do not implement `createUser()` its already there in `auth.controller.ts`. Please review once `auth.controller.ts`.

**Comment by MTouthang** [comment]
> @MTouthang , do not implement `createUser()` its already there in `auth.controller.ts`. Please review once `auth.controller.ts`.

sure got it

**Comment by sub1120** [comment]
@MTouthang I have divided this issue into 4 issues #33 #34 #35 #36. Assigned you #33 for now.
